default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres@localhost/tota_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres@localhost/tota_test") %>

production:
  <<: *default
  database: tota_production
  username: tota
  password: <%= ENV['TOTA_DATABASE_PASSWORD'] %>
