themes:
  - slug: general_insights
    title: General Insights
    widgets:
      - slug: size_tourism_region
        title: Size of regions (km2)
        description: |
          Total size of all BC regions, based on the administritive boundaries of tourism regions. Overall, BC has a territory of 922,000 km².
        indicators:
          - size_tourism_region_km2
        sources:
          - text: DestinationBC - Regional Profiles
            link: https://www.destinationbc.ca/research-insights/type/regional-research/regional-profiles/

      - slug: population
        title: Population
        description: |
          Total population per participating region. The most populated regions are Vancouver Island and Thompson Okanagan. The total population of BC is 4,892,084 people.
        note: New census data for 2021 coming soon.
        indicators:
          - population_by_tourism_region
        sources:
          - text: Statistics Canada - Census Data
            link: https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/index-eng.cfm

      - slug: tourism_revenue
        title: Tourism revenue
        description: Total amount of revenue generated by the tourism industry in the province.
        indicators:
          - revenue_tourism
        sources:
          - text: Destination BC - Value of Tourism
            link: https://www.destinationbc.ca/research-insights/type/industry-performance/?value-of-tourism=true

      - slug: gdp_total
        title: GDP Total
        description: To be defined
        indicators:
          - gdp_total

      - slug: gdp_tourism
        title: Tourism GDP Contribution
        description: To be defined
        indicators:
          - gdp_tourism
          - gdp_tourism_bc

      - slug: gdp_tourism_by_sector
        title: Share of tourism revenue by sub-sectors
        description: |
          Contribution of different tourism sub-sectors to the total tourism revenues in the province.
        indicators:
          - gdp_tourism_percentage_by_sector
        sources:
          - text: Destination BC - Value of Tourism
            link: https://www.destinationbc.ca/research-insights/type/industry-performance/?value-of-tourism=true

      - slug: tourism_employment
        title: Employment
        description: |
          Total number of people employed in the tourism industry in the province (& share of total employment).
        note: |
          Figures include full and part time employment. Data is presented for tourism regions, not economic regions (see map for the difference in administrative boundaries). See the header for BC totals.
        sources:
          - text: Statistics Canada - Labour Force Survey
            link: https://www.statcan.gc.ca/en/survey/household/3701
        indicators:
          - tourism_employment_by_tourism_region_annually
          - total_employment_by_tourism_region_annually


  - slug: tourism_industry_arrivals
    title: Tourism Industry & Arrivals
    widgets:
      - slug: tourism_businesses
        title: Tourism businesses
        sub_title: (by type)
        description: |
          Total number of tourism businesses in the selected region, by type of business.
        sources:
          - text: |
              Aggregated figures. Includes information directly from the regional DMOs, as well as additional business information of the tourism supply side from third party sources (e.g. campgrounds, visitor information centres, etc.).
        indicators:
          - establishments_by_type

      - slug: tourism_businesses_by_characteristic
        title: 'Tourism businesses: specific characteristics'
        description: |
          Total number of tourism businesses in the selected region that are: (1) members of the Biosphere program; (2) accessible businesses; (3) businesses that have indigenous ownership (51% and more).
        note: |
          The accessibility indication is not based on any official certifications or audits and should only be seen as indicative information.
          The highlighted businesses include a wide range of accessibility features.
          Please contact the individual business for detailed and specific accessibility information.
        sources:
          - text: |
              Regional DMOs and other relevant third party sources (e.g. Indigenous Tourism BC)
        indicators:
          - establishments_by_type

      - slug: domestic_arrivals
        title: Domestic arrivals
        description: Total amount of domestic overnight arrivals to the province/regions by month.
        note: |
          <br/>
          Visits: count of domestic travelers who spent one or more nights in the destination. Includes repeat visitation e.i. visitors are counted 1x on one month although came twice.
          Trips: count of domestic traveler trips which involved spending one or more nights over a certain time period as part of a continuous visit to the destination. includes unique visitors i.e. visitors that came twice in e.g. one month are counted as two trips.
          Stays: count of unique nights a domestic visitor was observed in the destination over a certain time period, i.e. overnights.
        sources:
          - text: Environics Analytics - VisitorView
        indicators:
          - visits_by_origin_country_monthly
          - trips_by_origin_country_monthly
          - stays_by_origin_country_monthly

      - slug: seasonality
        title: Seasonality
        description: Share of annual domestic overnight visitors occurring in peak month and quarter.
        sources:
          - text: Environics Analytics - VisitorView
        indicators:
          - domestic_visits_percentage_monthly
          - domestic_visits_percentage_quarterly

      - slug: seasonality_peak_vs_lowest
        title: 'Seasonality: peak month vs. lowest month'
        description: Ratio of domestic visitors in peak month to lowest month.
        sources:
          - text: Environics Analytics - VisitorView
        indicators:
          - domestic_visits_peak_lowest_month_ratio

      - slug: domestic_visitors_by_province
        title: Domestic visitors by province of origin
        description: Total domestic overnight visitors by their respective province of origin.
        sources:
          - text: Environics Analytics - VisitorView
        indicators:
          - visits_by_origin_province_monthly
          - visits_by_origin_province_quarterly

      - slug: domestic_overnight_visitors_by_city
        title: Domestic overnight visitors by city of origin
        sub_title: (top 10)
        description: Total domestic overnight visitors by their respective city of origin and by quarter.
        sources:
          - text: Environics Analytics - VisitorView
        indicators:
          - visits_by_origin_city_quarterly

      - slug: market_segmentation
        title: Market Segmentation Insights
        sub_title: (top 10)
        description: |
          Top 10 PRIZM clusters showing the largest lifestyle groups/top markets of potential domestic visitors per month for the selected region (total numbers).
        sources:
          - text: Environics Analytics - VisitorView
        indicators:
          - visits_by_prizm_monthly

      - slug: length_of_stay
        title: Length of stay
        description: Average length of stay of domestic overnight visitors in the seleted region (by days).
        sources:
          - text: Environics Analytics - VisitorView
        indicators:
          - nights_per_visitor_by_country_monthly

      - slug: travel_patterns
        title: Travel patterns of domestic overnight visitors
        description: |
          Weekly travel patterns of domestic overnight visitors showing the variation in volumes between the current year and the selected year.
        sources:
          - text: Environics Analytics - Measuring Canadian Travel Patterns
        indicators:
          - visits_change_weekly


  - slug: tourism_employment
    title: Tourism Employment
    widgets:
      - slug: economic_vs_tourism_region
        title: Economic region vs Tourism region
        description: |
          Due to different sources and their varying monitoring approaches, the information presented in this section is related to different regional administrative boundaries (either economic regions or tourism regions). To see the different boundaries, please go to the map.

      - slug: total_employment
        title: Total Employment
        description: Total number of people employed in the selected region (see the header for totals).
        note: Figures include full and part time employment. Data is presented for economic regions.
        sources:
          - text: Statistics Canada - Labour Force Surver
            link: https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410038702
        indicators:
          - total_employment_by_economic_region

      - slug: unemployment_rate
        title: Unemployment rate
        description: Unemployment rates for the selected regions by month.
        note: Figures include full and part time employment. Data is presented for economic regions.
        sources:
          - text: Statistics Canada - Labour Force Surver
            link: https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410038702
        indicators:
          - total_unemployment_rate_by_economic_region

      - slug: total_tourism_employment
        title: Total tourism employment
        description: Total tourism employment in the selected regions per month.
        note: Figures include full and part time employment. Data is presented for tourism regions.
        sources:
          - text: Go2HR Employment Tracker
            link: https://www.go2hr.ca/bc-tourism-and-hospitality-labour-market-information-employment-tracker
            note: based on Labour Force Survey information, but data is selected and transformed, focusing on specific tourism and hospitality occupations and presenting it for specifically for the tourism regions
        indicators:
          - tourism_employment_by_tourism_region_monthly

      - slug: tourism_to_total_employment
        title: Percentage of tourism employment to total employment
        description: Monthly and annual percentage share of tourism employment to total employment in the selected region.
        note: These figures should only be seen as inficative as they have two different regional boundaries as the basis for their presentation (economic region for total employment and tourism region for tourism employment).
        sources:
          - text: Statistics Canada - Labour Force Survey
            link: https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410038702
          - text: Go2HR Employment Tracker
            link: https://www.go2hr.ca/bc-tourism-and-hospitality-labour-market-information-employment-tracker
        indicators:
          - tourism_to_total_employment_percentage_monthly
          - tourism_to_total_employment_percentage_annually

      - slug: tourism_employment_by_sector
        title: Tourism employment by subsector
        description: Share of monthly tourism employment by different sub-sectors in the selected region.
        note: Figures include full and part time employment. Data is presented for tourism regions.
        sources:
          - text: Go2HR Employment Tracker
            link: https://www.go2hr.ca/bc-tourism-and-hospitality-labour-market-information-employment-tracker
            note: based on Labour Force Survey information, but data is selected and transformed, focusing on specific tourism and hospitality occupations and presenting it for specifically for the tourism regions
        indicators:
           - tourism_employment_by_sector_by_economic_region

      - slug: average_tourism_wages
        title: Average tourism related wages
        description: Average hourly earning (CAD$) by month in the selected region compared to the provincial average.
        note: Figures include full and part time employment. Data is presented for tourism regions, not economic regions (see map for the difference in administrative boundaries).
        sources:
          - text: Go2HR Employment Tracker
            link: https://www.go2hr.ca/bc-tourism-and-hospitality-labour-market-information-employment-tracker
            note: based on Labour Force Survey information, but data is selected and transformed, focusing on specific tourism and hospitality occupations and presenting it for specifically for the tourism regions
        indicators:
          - tourism_employment_hourly_earnings_by_economic_region

      - slug: employment_by_job_status
        regions_whitelist:
          - british_columbia
        title: Employment by job status
        description: Shares of full time and part time empployment in tourism and its sub-sectors for the seclected regions.
        sources:
          - text: Go2HR Employment Tracker
            link: https://www.go2hr.ca/bc-tourism-and-hospitality-labour-market-information-employment-tracker
            note: based on Labour Force Survey information, but data is selected and transformed, focusing on specific tourism and hospitality occupations and presenting it for specifically for the tourism regions
        indicators:
          - tourism_employment_by_job_status


  - slug: tourism_development_funds
    title: Tourism Development Funds
    widgets:
      - slug: total_funding_and_projects
        title: Total funding and projects
        description: |
          Total number of funding amounts (CAD$) per funding stream and total number of funded projects per year, per stream.
        note: |
          Open funding calls can be found <a href="https://strongerbc.gov.bc.ca/supporting-bc-businesses" target="_blank" rel="noopener noreferrer">here (TRTD / Stronger BC)</a>
        sources:
          - text: BC Government (TRTD / StrongerBC)
            link: https://strongerbc.gov.bc.ca/supporting-bc-businesses
        indicators:
          - development_funds_by_source
          - development_funds_volume_by_source

      - slug: funded_project_details
        title: Funded project details
        description: Click below to see projects on the map page.
        indicators:
          - development_funds_by_source
          - development_funds_volume_by_source


  - slug: airport_information
    title: Airport Information
    widgets:
      - slug: airport_arrivals
        title: Number of arriving flights
        description: Total number of flights arriving to the top 3 airports per selected region.
        note: Flights per destination include all airlines serving that route.
        sources:
          - text: Individual airports
        indicators:
          - airport_arrivals_monthly

      - slug: passenger_volume
        title: Total passenger volume
        description: Total air passenger arrivals to the top 3 airports per selected region.
        sources:
          - text: Individual airports
        indicators:
          - airport_domestic_pax_monthly
          - airport_international_pax_monthly

      - slug: int_vs_dom_arrivals
        title: International vs. domestic arrivals
        description: Share of international and domestic air passenger arrivals to the top 3 airport per selected region.
        note: Passenger splits are based on O/D data.
        sources:
          - text: Individual airports
        indicators:
          - airport_dom_arrivals_monthly
          - airport_int_arrivals_monthly

      - slug: airport_connections
        title: Airport connections
        description: Total number of destinations the airport is directly connected with (per year).
        sources:
          - text: Individual airports
        indicators:
          - airport_total_destinations

      - slug: top_connections_per_week
        title: Top connections per week
        description: |
          Most frequent flight activity per week between the selected airport and its available destinations (based on averages).
        sources:
          - text: Individual airports
        indicators:
          - airport_top_average_connections_per_week

      - slug: daily_arrivals
        title: Daily arrivals by origin airport
        description: |
          Average daily number of flights arriving to the selected airport by origin airport (per month).
        sources:
          - text: Individual airports
        indicators:
          - airport_arrivals_by_origin_daily


  - slug: accommodation_information
    title: Accommodation Information
    widgets:
      - slug: occupancy_rates
        title: Occupancy rates
        description: |
          Occupancy rate of hotels in the selected region. Shown are the average rates during the week vs. weekends (%) and the percentage change to the previous year. The historical data shows the development over time per year.
        note: |
          Insights of hotels participating in the STR report. Occupancy rates are calculated by dividing the the number of occupied rooms by the number of available rooms that physically exist in a hotel. To participate in the STR "STAR" Report, hotels can submit data and receive free reports benchmarking performance against market trends. To enroll, see here.
        sources:
          - text: STR/NCHA/BCRTS Destination Weekly Reports
        indicators:
          - occupancy_weekday
          - occupancy_weekend
          - occupancy_change_weekend
          - occupancy_change_weekday
          - occupancy_month
          - occupancy_change_month
          - occupancy_week

      - slug: average_daily_hotel_rate
        title: Average daily hotel rate (ADR)
        description: |
          Average daily hotel rate (ADRs) of hotels in the selected region during the week vs. weekends (%) and the percentage change to the previous year. The historical data shows the development over time per year.
        note: |
          Insights of hotels participating in the STR report. Occupancy rates are calculated by dividing the the number of occupied rooms by the number of available rooms that physically exist in a hotel. To participate in the STR "STAR" Report, hotels can submit data and receive free reports benchmarking performance against market trends. To enroll, see here.
        sources:
          - text: STR/NCHA/BCRTS Destination Weekly Reports
        indicators:
          - adr_weekday
          - adr_weekend
          - adr_change_weekend
          - adr_change_weekday
          - adr_month
          - adr_change_month
          - adr_week

      - slug: revenue_per_available_room
        title: Revenue per available room (RevPAR)
        description: |
          Revenue per available room (RevPAR) of hotels in the selected region during the week vs. weekends (%) and the percentage change to the previous year. The historical data shows the development over time per year.
        note: |
          Insights of hotels participating in the STR report. Occupancy rates are calculated by dividing the the number of occupied rooms by the number of available rooms that physically exist in a hotel. To participate in the STR "STAR" Report, hotels can submit data and receive free reports benchmarking performance against market trends. To enroll, see here.
        sources:
          - text: STR/NCHA/BCRTS Destination Weekly Reports
        indicators:
          - revpar_weekday
          - revpar_weekend
          - revpar_change_weekend
          - revpar_change_weekday
          - revpar_month
          - revpar_change_month
          - revpar_week
