import uniq from 'lodash/uniq';

import { ThemeType, IndicatorValue } from 'types';
import { previousYear, thisYear, compactNumberTickFormatter, moneyTickFormatter } from './utils';
import { defaultTooltip } from 'constants/charts';
import {
  filterBySelectedYear,
  getColorsByRegionName,
  getStackedBarsData,
  getAvailableYearsOptions,
  getUnitLabel,
  mergeForChart,
} from 'utils/charts';
import { REGION_COLORS } from 'constants/regions';

const theme: ThemeType = {
  title: 'General Insights',
  slug: 'general-insights',
  sections: [
    {
      title: 'Size of regions (km2)',
      description: `Total size of all BC regions, based on the administritive boundaries of tourism regions. Overall, BC has a territory of 922,000 km².`,
      sources: [
        {
          text: 'DestinationBC - Regional Profiles',
          link: 'https://www.destinationbc.ca/research-insights/type/regional-research/regional-profiles/',
        },
      ],
      initialState: {
        year: thisYear,
      },
      fetchParams: (state) => ({
        slug: 'size_tourism_region_km2',
        region: state.selectedRegion.children?.map((x) => x.slug),
      }),
      fetchWidgetProps(rawData: IndicatorValue[] = [], state: any): any {
        const data = filterBySelectedYear(rawData, state.year);

        return {
          type: 'charts/treemap',
          data: data.map((d) => ({
            name: d.region,
            color: REGION_COLORS[d.region_slug],
            value: d.value,
          })),
          tooltip: {
            valueFormatter: (v) => `${Number(v).toLocaleString()} km2`,
          },
          controls: [
            { type: 'select', side: 'right', name: 'year', options: getAvailableYearsOptions(rawData, false) },
          ],
        };
      },
    },
    {
      title: 'Population',
      description: `Total population per participating region. The most populated regions are Vancouver Island and Thompson Okanagan. The total population of BC is 4,892,084 people.`,
      note: 'New census data for 2021 coming soon.',
      sources: [
        {
          text: 'Statistics Canada - Census Data',
          link: 'https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/index-eng.cfm',
        },
      ],
      initialState: {
        year: thisYear,
      },
      fetchParams: (state) => ({
        slug: 'population_by_tourism_region',
        region: state.selectedRegion.children?.map((x) => x.slug),
      }),
      fetchWidgetProps(rawData: IndicatorValue[] = [], state: any): any {
        const data = filterBySelectedYear(rawData, state.year).map((d) => ({
          ...d,
          color: REGION_COLORS[d.region_slug],
        }));

        return {
          type: 'charts/pie',
          data,
          controls: [
            { type: 'select', side: 'right', name: 'year', options: getAvailableYearsOptions(rawData, false) },
          ],
          pies: [
            {
              nameKey: 'region',
              dataKey: 'value',
              label: function ({ value }) {
                return Number(value).toLocaleString();
              },
            },
          ],
        };
      },
    },
    {
      title: 'Tourism revenue',
      description: `Total amount of revenue generated by the tourism industry in the province.`,
      sources: [
        {
          text: 'Destination BC - Value of Tourism',
          link: 'https://www.destinationbc.ca/research-insights/type/industry-performance/?value-of-tourism=true',
        },
      ],
      fetchParams: (state: any) => ({
        slug: 'revenue_tourism',
        region: state.selectedRegion.slug,
      }),
      fetchWidgetProps(rawData: IndicatorValue[] = [], state: any): any {
        const chartData = mergeForChart({ data: rawData, mergeBy: 'date', labelKey: 'region', valueKey: 'value' });
        const colorsByRegionName = getColorsByRegionName(rawData);
        const regions = uniq(rawData.map((x) => x.region)).map((x) => ({ dataKey: x, color: colorsByRegionName[x] }));

        return {
          type: 'charts/line',
          data: chartData,
          lines: regions,
          chartProps: {
            margin: {
              top: 60,
              left: 10,
            },
          },
          xAxis: {
            dataKey: 'date',
          },
          yAxis: {
            label: getUnitLabel('million $'),
            tickFormatter: (v) => Number(v).toLocaleString(),
          },
          tooltip: {
            ...defaultTooltip,
            valueFormatter: (v) => `${Number(v).toLocaleString()} million CAD$`,
          },
        };
      },
    },
    {
      title: 'GDP Total',
      description: `To be defined`,
      fetchParams: (state: any) => ({
        slug: 'gdp_total',
        region: state.selectedRegion.slug,
      }),
      fetchWidgetProps(rawData: IndicatorValue[] = [], _state: any): any {
        const indicatorsMap = {
          gdp_total: 'Total',
        };
        const changed = rawData.map((x) => ({ ...x, indicator: indicatorsMap[x.indicator] }));
        const data = mergeForChart({ data: changed, mergeBy: 'date', labelKey: 'indicator', valueKey: 'value' });

        return {
          type: 'charts/bar',
          data,
          bars: Object.values(indicatorsMap).map((x) => ({ dataKey: x })),
          chartProps: {
            margin: {
              top: 60,
              left: 10,
            },
          },
          tooltip: {
            cursor: false,
            valueFormatter: (v) => `${Number(v).toLocaleString()} million CAD$`,
          },
          xAxis: {
            dataKey: 'date',
          },
          yAxis: {
            label: getUnitLabel('million $'),
            tickFormatter: (v) => Number(v).toLocaleString(),
          },
        };
      },
    },
    {
      title: 'Tourism GDP Contribution',
      description: `To be defined`,
      initialState: {
        indicator: 'gdp_tourism',
      },
      fetchParams: (state: any) => ({
        slug: state.indicator,
        region: state.selectedRegion.slug,
      }),
      fetchWidgetProps(rawData: IndicatorValue[] = [], state: any): any {
        const indicatorsMap = {
          gdp_tourism: 'Tourism',
          gdp_tourism_bc: 'Tourism',
        };
        const changed = rawData.map((x) => ({ ...x, indicator: indicatorsMap[x.indicator] }));
        const data = mergeForChart({ data: changed, mergeBy: 'date', labelKey: 'indicator', valueKey: 'value' });

        return {
          type: 'charts/bar',
          data,
          controls: [
            {
              type: 'tabs',
              side: 'left',
              name: 'indicator',
              options: [
                {
                  value: 'gdp_tourism',
                  label: 'Total',
                },
                {
                  value: 'gdp_tourism_bc',
                  label: 'Percentage',
                },
              ],
            },
          ],
          bars: [{ dataKey: indicatorsMap[state.indicator], stackId: 1 }],
          chartProps: {
            margin: {
              top: 60,
              left: 10,
            },
          },
          xAxis: {
            dataKey: 'date',
          },
          ...(state.indicator === 'gdp_tourism' && {
            yAxis: {
              label: getUnitLabel('million $'),
              tickFormatter: (v) => Number(v).toLocaleString(),
            },
            tooltip: {
              cursor: false,
              valueFormatter: (v) => `${Number(v).toLocaleString()} million CAD$`,
            },
          }),
          ...(state.indicator === 'gdp_tourism_bc' && {
            yAxis: {
              tickFormatter: (v) => `${v}%`,
            },
            tooltip: {
              cursor: false,
              valueFormatter: (v) => `${Number(v).toLocaleString()}%`,
            },
          }),
        };
      },
    },
    {
      title: 'Share of tourism revenue by sub-sectors',
      description: `Contribution of different tourism sub-sectors to the total tourism revenues in the province.`,
      sources: [
        {
          text: 'Destination BC - Value of Tourism',
          link: 'https://www.destinationbc.ca/research-insights/type/industry-performance/?value-of-tourism=true',
        },
      ],
      initialState: {
        year: previousYear,
      },
      fetchParams: (state: any) => ({
        slug: 'gdp_tourism_percentage_by_sector',
        region: state.selectedRegion.slug,
      }),
      fetchWidgetProps(rawData: IndicatorValue[] = [], state: any): any {
        const data = filterBySelectedYear(rawData, state.year);

        return {
          type: 'charts/pie',
          data,
          controls: [
            { type: 'select', side: 'right', name: 'year', options: getAvailableYearsOptions(rawData, false) },
          ],
          pies: [
            {
              nameKey: 'category_1',
              dataKey: 'value',
              label: function ({ value }) {
                return `${value}% `;
              },
            },
          ],
          tooltip: {
            ...defaultTooltip,
            valueFormatter: (value) => {
              return `${value}% `;
            },
          },
        };
      },
    },
    {
      title: 'Employment',
      description: `Total number of people employed in the tourism industry in the province (& share of total employment).`,
      note: 'Figures include full and part time employment. Data is presented for economic regions, not tourism regions (see map for the difference in administrative boundaries). See the header for BC totals.',
      sources: [
        {
          text: 'Statistics Canada - Labour Force Survey',
          link: 'https://www.statcan.gc.ca/en/survey/household/3701',
        },
      ],
      initialState: {
        year: previousYear,
      },
      fetchParams: (state: any) => ({
        slug: ['tourism_employment_by_tourism_region_annually', 'total_employment_by_tourism_region_annually'],
        region: state.selectedRegion.children?.map((x) => x.slug),
      }),
      fetchWidgetProps(rawData: IndicatorValue[] = [], state: any): any {
        const indicatorsMap = {
          tourism_employment_by_tourism_region_annually: 'Tourism',
          total_employment_by_tourism_region_annually: 'Total',
        };
        const changed = filterBySelectedYear(rawData, state.year).map((x) => ({
          ...x,
          indicator: indicatorsMap[x.indicator],
        }));
        const data = mergeForChart({
          data: changed,
          mergeBy: 'region',
          labelKey: 'indicator',
          valueKey: 'value',
        });
        const bars = getStackedBarsData(data, 'region');

        return {
          type: 'charts/bar',
          data,
          controls: [
            { type: 'select', side: 'right', name: 'year', options: getAvailableYearsOptions(rawData, false) },
          ],
          chartProps: {
            layout: 'vertical',
          },
          bars,
          xAxis: {
            hide: true,
            type: 'number',
          },
          yAxis: {
            dataKey: 'region',
            type: 'category',
          },
        };
      },
    },
  ],
};

export default theme;
