import { ThemeType } from 'types';

const theme: ThemeType = {
  title: 'General Insights',
  slug: 'general-insights',
  summary:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eget risus sollicitudin, ullamcorper nunc eu, auctor ligula. Sed sodales aliquam nisl eget mollis. Quisque mollis nisi felis, eu convallis purus sagittis sit amet.',
  sections: [
    {
      title: 'Population',
      description: `Total provincial/regional population with working age of 15 years and older.`,
      initialState: {
        year: '2020',
      },
      fetchParams: () => null,
      fetchWidgetProps(): any {
        return {
          type: 'text',
          data: 'Data placeholder',
        };
      },
    },
    {
      title: 'Tourism contribution to GDP',
      description: `Contribution of the tourism industry to the provincial GDP (total and % of GDP)`,
      fetchParams: () => null,
      fetchWidgetProps(): any {
        return {
          type: 'text',
          data: 'Data placeholder',
        };
      },
    },
    {
      title: 'Employment',
      description: `Total number of people employed in the tourism industry in the province (& share of total employment)`,
      fetchParams: () => null,
      fetchWidgetProps(): any {
        return {
          type: 'text',
          data: 'Data placeholder',
        };
      },
    },
    {
      title: 'Tourism revenue',
      description: `Total amount of revenue generated by the tourism industry in the province and regional shares.`,
      fetchParams: () => null,
      fetchWidgetProps(): any {
        return {
          type: 'text',
          data: 'Data placeholder',
        };
      },
    },
  ],
};

export default theme;
