version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tota_development
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
      DATABASE_URL: postgres://postgres:postgres@db/tota_development
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  pgdata: