source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.0'

gem 'rails', '~> 7.0.1'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'

gem 'activerecord-import'

# API
gem 'blueprinter'
gem 'rack-cors'

# Backoffice
gem 'jsbundling-rails'
gem 'cssbundling-rails'
gem 'turbo-rails'
gem 'stimulus-rails'
gem 'sprockets-rails'

gem 'pagy'

gem 'acts_as_list'
gem 'devise'
gem 'pundit'
gem 'ransack'
gem 'simple_form'
gem 'store_model'

gem 'appsignal'

gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'annotate'
  gem 'brakeman', require: false
  gem 'bundler-audit', require: false
  gem 'letter_opener_web'
  gem 'listen', '~> 3.3'
  gem 'pry', '~> 0.13.1'
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'web-console', '>= 4.1.0'
  gem 'capistrano', '~> 3.15', require: false
  gem 'capistrano-maintenance', '~> 1.2', require: false
  gem 'capistrano-rails', '~> 1.6', require: false
  gem 'capistrano-rbenv', '~> 2.2'
  gem 'capistrano-bundler'
  gem 'capistrano3-puma'
  gem 'capistrano-yarn'
  gem 'capistrano-nvm'

  # required for emacs robe mode
  gem 'pry-doc', require: false
  gem 'webrick', require: false
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'cuprite'
  gem 'rspec-collection_matchers'
  gem 'rspec-rails', '~> 5.0.0'
  gem 'rspec-request_snapshot'
  gem 'factory_bot_rails'
  gem 'simplecov', require: false
  gem 'super_diff'
  gem 'test-prof'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Use Redis for Action Cable
gem 'redis', '~> 4.0'
