export const typesOfTourismEstablishments = {
  data: [
    {
      slug: 'establishments_by_type',
      indicator_values: [
        {
          category_1: 'Food & Beverage',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 641,
        },
        {
          category_1: 'Cultural (Museum, Gallery, Festivals, Etc)',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 160,
        },
        {
          category_1: 'Ski',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 34,
        },
        {
          category_1: 'Tour Product (Wildlife Viewing, Tour Guide, Etc)',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 75,
        },
        {
          category_1: 'Rentals',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 22,
        },
        {
          category_1: 'Retail',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 36,
        },
        {
          category_1: 'Independent / Contractor',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 15,
        },
        {
          category_1: 'Government',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 26,
        },
        {
          category_1: 'Accommodation',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 1309,
        },
        {
          category_1: 'Visitor Servicing',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 64,
        },
        {
          category_1: 'Services',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 120,
        },
        {
          category_1: 'Associations',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 44,
        },
        {
          category_1: 'Dmo',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 11,
        },
        {
          category_1: 'Media',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 23,
        },
        {
          category_1: 'Transportation',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 50,
        },
        {
          category_1: 'Activity / Attraction',
          category_2: 'all',
          date: null,
          region: 'Thompson Okanagan',
          value: 656,
        },
        {
          category_1: 'Accommodation',
          category_2: 'biosphere',
          date: null,
          region: 'Thompson Okanagan',
          value: 10,
        },
        {
          category_1: 'Activity / Attraction',
          category_2: 'biosphere',
          date: null,
          region: 'Thompson Okanagan',
          value: 8,
        },
        {
          category_1: 'Dmo',
          category_2: 'biosphere',
          date: null,
          region: 'Thompson Okanagan',
          value: 4,
        },
        {
          category_1: 'Food & Beverage',
          category_2: 'biosphere',
          date: null,
          region: 'Thompson Okanagan',
          value: 14,
        },
        {
          category_1: 'Rentals',
          category_2: 'biosphere',
          date: null,
          region: 'Thompson Okanagan',
          value: 1,
        },
        {
          category_1: 'Services',
          category_2: 'biosphere',
          date: null,
          region: 'Thompson Okanagan',
          value: 1,
        },
        {
          category_1: 'Ski',
          category_2: 'biosphere',
          date: null,
          region: 'Thompson Okanagan',
          value: 1,
        },
      ],
    },
  ],
};
