export const PROPERTIES_NEW_NAMES = {
  accommodations: {
    custodianOrgDescription: 'source',
  },
  campgrounds: {
    sites: 'nrOfSites',
    units: 'nrOfUnits',
  },
  fires: {
    cartodbId: 'id',
    dateStr: 'date',
  },
  first_nations_communities: {
    alternativeName1: 'alternativeName',
    urlToFirstNationWebsite: 'website',
  },
  ski_resorts: {
    custodianOrgDescription: 'source',
  },
};

export const PROPERTIES_TO_PICK = {
  airports: [
    'airportName',
    'description',
    'streetAddress',
    'locality',
    'latitude',
    'longitude',
    'iataCode',
    'icaoCode',
    'custodianOrgDescription',
    'occupantTypeDescription',
    'dataSource',
  ],
  accommodations: [
    'occupantName',
    'description',
    'businessCategoryDescription',
    'keywords',
    'longitude',
    'latitude',
    'physicalAddress',
    'postalCode',
    'tourismArea',
    'facebookAccount',
    'twitterAccount',
    'source',
  ],
  campgrounds: ['name', 'longitude', 'latitude', 'address', 'city', 'postalCode', 'nrOfSites', 'nrOfUnits'],
  fires: ['id', 'date', 'longitude', 'latitude', 'daysAgo'],
  first_nations_communities: [
    'firstNationBcName',
    'firstNationFederalName',
    'preferredName',
    'alternativeName',
    'languageGroup',
    'memberOrganizationNames',
    'bcRegionalOffice',
    'addressLine1',
    'addressLine2',
    'officeCity',
    'officeProvince',
    'officePostalCode',
    'siteName',
    'siteNumber',
    'location',
    'description',
    'comments',
    'website',
  ],
  ski_resorts: [
    'facilityName',
    'businessCategoryDescription',
    'keywords',
    'longitude',
    'latitude',
    'physicalAddress',
    'source',
  ],
  stops: ['signName', 'currentText', 'longitude', 'latitude', 'specificLocation'],
  visitor_centers: [
    'name',
    'businessType',
    'longitude',
    'latitude',
    'address',
    'postalCode',
    'tourismRegion',
    'tourismSubRegion',
  ],
};
