export const PROPERTIES_MAP = {
  airports: {
    airportName: 'Airport Name',
    streetAddress: 'Street Address',
    locality: 'Locality',
    latitude: 'Latitude',
    longitude: 'Longitude',
    iataCode: 'IATA Code',
    icaoCode: 'ICAO Code',
    custodianOrgDescription: 'Custodian Org Description',
    occupantTypeDescription: 'Occupant Type Description',
    dataSource: 'Data Source',
  },
  accommodations: {
    occupantName: 'Occupant Name',
    description: 'Description',
    businessCategoryDescription: 'Business Category Description',
    keywords: 'Keywords',
    longitude: 'Longitude',
    latitude: 'Latitude',
    physicalAddress: 'Physical Address',
    postalCode: 'Postal Code',
    tourismArea: 'Tourism Area',
    facebookAccount: 'Facebook Account',
    twitterAccount: 'Twitter Account',
    custodianOrgDescription: 'Source',
  },
  campgrounds: {
    name: 'Name',
    longitude: 'Longitude',
    latitude: 'Latitude',
    address: 'Address',
    city: 'City',
    postalCode: 'Postal Code',
    sites: {
      name: 'Nr. of Sites',
      info: 'Available spots for tents or RVs etc. (not differentiated by available services like electricity etc.',
    },
    units: 'Nr. of Units',
  },
  development_funds: {
    projectTitle: 'Project Title',
    projectDescription: 'Project Description',
    recipient: 'Recipient',
    leadOrganization: 'Lead Organization',
    keyFundingAmount: 'Key Funding Amount ($CAD)',
    keyFundingSource: 'Key Funding Source',
    fundingSubtype: 'Funding Sub-type',
    fundingCallYear: 'Funding Call Year',
    fundingCallMonth: 'Funding Call Month',
  },
  fires: {
    cartodbId: 'Id',
    dateStr: 'date',
    longitude: 'Longitude',
    latitude: 'Latitude',
    daysAgo: 'Days ago',
  },
  first_nations_business: {
    businessName: 'Business Name',
    occupantTypeDescription: '',
    companyType: 'Company Type',
    streetAddress: 'Street Address',
    postalCode: 'Postal Code',
    locality: 'Locality',
    longitude: 'Longitude',
    latitude: 'Latitude',
    yearFormed: 'Year Formed',
    description: 'Description',
    custodianOrgDescription: 'Source',
  },
  first_nations_communities: {
    firstNationBcName: 'First Nation BC Name',
    firstNationFederalName: 'First Nation Federal Name',
    preferredName: 'Preferred Name',
    alternativeName1: 'Alternative Name',
    languageGroup: 'Language Group',
    memberOrganizationNames: 'Member Organization Names',
    bcRegionalOffice: 'BC Regional Office',
    addressLine1: 'Address Line1',
    addressLine2: 'Address Line2',
    officeCity: 'Office City',
    officeProvince: 'Office Province',
    officePostalCode: 'Office Postal Code',
    siteName: 'Site Name',
    siteNumber: 'Site Number',
    location: 'Location',
    description: 'Description',
    comments: 'Comments',
    urlToFirstNationWebsite: 'Website',
  },
  ski_resorts: {
    facilityName: 'Facility Name',
    businessCategoryDescription: 'Business Category Description',
    keywords: 'Keywords',
    longitude: 'Longitude',
    latitude: 'Latitude',
    physicalAddress: 'Physical Address',
    custodianOrgDescription: 'Source',
  },
  stops: {
    signName: 'Sign Name',
    currentText: 'Current Text',
    longitude: 'Longitude',
    latitude: 'Latitude',
    specificLocation: 'Specific Location',
  },
  trails: {
    projectType: 'Project Type',
    projectName: 'Project Name',
    siteLocation: 'Site Location',
    projectEstablishedDate: 'Project Established Date',
    definedCampsites: 'Defined Campsites',
    fileStatusCode: 'File Status Code',
    districtCode: 'District Code',
    districtName: 'District Name',
    featureLengthM: 'Feature Length (m)',
    tourismRegionName: 'Tourism Region Name',
  },
  visitor_centers: {
    name: 'Name',
    businessType: 'Business Type',
    longitude: 'Longitude',
    latitude: 'Latitude',
    address: 'Address',
    postalCode: 'Postal Code',
    tourismRegion: 'Tourism Region',
    tourismSubRegion: 'Tourism Subregion',
  },
  wildlife_habitats: {
    featureNotes: 'Feature Notes',
    commonSpeciesName: 'Common Species Name',
    timberHarvestCode: 'Timber Harvest Code',
    hectares: 'Hectares',
    featureAreaSqm: 'Feature Area (sqm)',
    featureLengthM: 'Feature Length (m)',
    tourismRegionName: 'Tourism Region',
  },
};
